=== iamsoojung/Health_info_system/health_info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="건강정보시스템">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="질병" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="질병">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="분류"/>
        <xs:element ref="질환명" maxOccurs="unbounded"/>
        <xs:element name="증상" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="정의" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="img" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="분류">
    <xs:complexType>
      <xs:attribute name="부위별" type="xs:string" use="required"/>
      <xs:attribute name="진료과별" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="질환명">
    <xs:complexType mixed="true">
      <xs:attribute name="language" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iamsoojung/Health_info_system/health_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="health_info.xsl"?>
<건강정보시스템 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="health_info.xsd">
  <!--가슴-->
  <질병>
    <분류 부위별="가슴" 진료과별="감염내과"/>
    <질환명 language="kor">RS바이러스 감염증</질환명>
    <질환명 language="eng">RS virus infection</질환명>
    <증상>빈호흡, 열, 가래, 기침, 청색증, 코막힘, 콧물</증상>
    <정의>RS 바이러스 감염증은 RS 바이러스에 감염되어 유발하는 감염성 호흡기 질환을 말합니다. RS 바이러스는 우리말로 호흡기 세포 융합 바이러스라고 합니다. 이는 만 2세까지 거의 모든 소아가 감염될 정도로 감염력이 높습니다. 이 바이러스에 한 번 감염되면 평생동안 지속적으로 재감염이 이루어집니다. 성인의 경우 가벼운 감기로 나타나는 경우가 많습니다. 하지만 면역 저하자 또는 노령층에서는 중증 감염이 유발될 수 있습니다.</정의>
    <img>image/chest/RS virus infection.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">급성 기관지염</질환명>
    <질환명 language="eng">Acute bronchitis</질환명>
    <증상>천명음, 가래, 기침, 호흡곤란</증상>
    <정의>급성 기관지염은 목구멍 뒤에 있는 폐로 들어가는 관인 기관에 바이러스, 세균 등의 병원균이 침입하여 급성 염증 반응이 생긴 것을 의미합니다. 유행성 독감과 같은 인플루엔자가 유행하면 급성 기관지염의 발생 빈도도 증가합니다.</정의>
    <img>image/chest/Acute bronchitis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">가습기 살균제 연관 폐질환</질환명>
    <질환명 language="eng">Humidifier disinfectant-associated lung injury</질환명>
    <증상>기침, 호흡곤란, 폐동맥 고혈압, 심부전, 다발성 장기부전 증상</증상>
    <정의>2011년 겨울에서 봄에 이르는 기간에 기저 질환이 없었던 젊은 여성을 중심으로 과거에 경험한 적 없는 치명적인 폐 질환이 발생하였습니다. 감기처럼 시작하지만, 기도를 중심으로 생긴 염증이 급속히 폐로 퍼지면서 폐가 단단해지는 폐 섬유화를 거쳐 호흡이 불가능해지고, 결국 사망까지 이르는 치명적인 질환입니다.</정의>
    <img>image/chest/Humidifier disinfectant-associated lung injury.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">객혈</질환명>
    <질환명 language="eng">Hemoptysis</질환명>
    <증상>가래, 거품이 섞인 가래, 객혈</증상>
    <정의>객혈은 기침과 함께 혈액이 섞인 가래가 나오는 것을 의미합니다. 기침할 때 흉통을 동반하는 경우가 많으며, 피는 대부분 선홍빛입니다. 객혈은 전체적인 양보다 속도가 중요합니다. 시간당 150mL 정도의 속도로 피가 나온다면 질식될 위험이 있습니다.</정의>
    <img>image/chest/Hemoptysis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="성형외과"/>
    <질환명 language="kor">거대 유방</질환명>
    <질환명 language="eng">Macromastia, Gigantomastia, large breast, hypermas</질환명>
    <증상></증상>
    <정의>유방 축소술이란 유방의 과도한 피부 및 유방 조직을 절제함으로써 거대 유방의 크기를 축소하고 미용적으로 보기 좋은 유방으로 만드는 수술 방법입니다. </정의>
    <img>image/chest/Macromastia, Gigantomastia, large breast, hypermas.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="감염내과"/>
    <질환명 language="kor">결핵</질환명>
    <질환명 language="eng">Tuberculosis</질환명>
    <증상>열, 가래, 기침, 체중감소, 객혈</증상>
    <정의>결핵은 결핵균이 침입하여 발생하는 병입니다. 결핵은 호흡기 분비물로 옮겨지는 전염성 질환으로, 환자와 접촉하는 가족 중에서 발생하는 경우가 많습니다. 누구든지 결핵에 걸릴 가능성이 있으나 결핵균이 침입한다고 해서 모두 다 발병하는 것은 아닙니다. 결핵균이 침입한 후 체내의 저항력이 약해지면 발병할 확률이 높아집니다.</정의>
    <img>image/chest/Tuberculosis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">공기가슴증(기흉)</질환명>
    <질환명 language="eng"> Pneumothorax</질환명>
    <증상>호흡곤란, 가슴 통증</증상>
    <정의>공기가슴증, 즉 기흉은 폐에 생긴 구멍으로 공기가 새면서 늑막강 안에 공기가 차는 질환을 의미합니다. 새는 공기의 양이 증가할수록 폐가 정상 기능을 하지 못합니다. 흉강 안으로 유입되는 공기가 배출되지 않는 경우 양쪽 폐와 심장 사이의 공간과 심장이 한쪽으로 쏠려 응급상황이 발생할 수 있습니다.</정의>
    <img>image/chest/Pneumothorax.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">과호흡 증후군</질환명>
    <질환명 language="eng">Hyperventilation syndrome</질환명>
    <증상>흉부압박감, 복부 통증, 가슴 두근거림, 호흡곤란, 부정맥, 복부팽만감, 인지장애, 의식 변화, 불안</증상>
    <정의>과호흡 증후군은 어떠한 이유에서든 과도한 호흡으로 인해 이산화탄소가 과다하게 배출되어 발생하는 질환을 의미합니다. 우리 몸은 정상적인 호흡을 통해 산소를 받아들이고 이산화탄소를 배출시킵니다. 그 결과 동맥혈(동맥 속의 혈액)의 이산화탄소 농도는 37~43mmHg 범위에서 유지됩니다. 동맥혈의 이산화탄소 농도가 정상 범위 아래로 떨어져서 호흡 곤란, 어지럼증, 저리고 마비되는 느낌, 실신 등의 증상이 나타납니다. 주로 젊은 여성에게서 잘 발생합니다.</정의>
    <img>image/chest/Hyperventilation syndrome.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="호흡기내과"/>
    <질환명 language="kor">규폐증</질환명>
    <질환명 language="eng">Silicosis</질환명>
    <증상>운동 시 호흡곤란, 가래, 기침</증상>
    <정의>규폐증은 규사 등의 먼지가 폐에 쌓여 흉터가 생기는 질환을 의미합니다. 규사 먼지는 다른 먼지 입자와 달리 폐 조직 내에서 강한 염증 반응을 일으킵니다. 시간이 지날수록 염증이 두터워지며, 이는 나중에 흉터로 변하여 산소 공급에 이상을 초래합니다. 담배를 피우는 경우 증상이 더 빨리, 더 심하게 악화됩니다.</정의>
    <img>image/chest/Silicosis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="가슴" 진료과별="심장내과"/>
    <질환명 language="kor">급성 관동맥 증후군</질환명>
    <질환명 language="eng">Acute Coronary Syndrome</질환명>
    <증상>오심, 호흡곤란, 어지러움, 가슴 통증, 방사통</증상>
    <정의>심장은 관상동맥에 의해 산소와 영양분을 공급받아 활동합니다. 급성 관동맥 증후군(ACS)은 관상동맥의 혈관 내에 급성으로 생긴 크고 작은 혈전으로 인해 순간적으로 혈관이 폐쇄되거나, 혈전에서 분비되는 여러 혈관 수축성 물질이 혈관을 더욱 심하게 수축시킴으로써 관상동맥이 심하게 폐쇄되어 심장에 혈류 공급이 부족해지는 질환을 의미합니다.</정의>
    <img>image/chest/Acute Coronary Syndrome.JPG</img>
  </질병>
  
  <!--골반-->
  <질병>
    <분류 부위별="골반" 진료과별="비뇨의학과"/>
    <질환명 language="kor">PSA 상승</질환명>
    <질환명 language="eng">Elevated PSA</질환명>
    <증상>무증상</증상>
    <정의>PSA(전립선 특이항원)는 전립선에서만 생성되는 단백질로 이는 정액의 액화에 관여합니다. 정액의 액화는 정액 검사를 하기 위해 컵에 정액을 받으면 처음에는 젤리 상태였다가 점점 묽어지는 현상을 말합니다. 이는 정자가 여성의 질 내에서 살아 남아 난자와 결합하는 과정에서 중요한 역할을 합니다. PSA는 전립선 조직, 특히 전립선, 도관의 내공 상피, 전립선 분비물에 존재하고 전립선에서만 나온다고 해서 전립선 특이라고 합니다. PSA 상승은 이러한 특이항원이 상승하는 질환을 말합니다.</정의>
    <img>image/pelvis/Elevated PSA.JPG</img>
  </질병>
   <질병>
    <분류 부위별="골반" 진료과별="산부인과"/>
    <질환명 language="kor">가진통</질환명>
    <질환명 language="eng">False labor</질환명>
    <증상>비정상적인 진통, 불규칙적 진통</증상>
    <정의>가진통은 출산 예정일이 다가올수록 자궁 수축이 자주 나타나지만 경관이 개대(열림)되지 않는 증상을 의미합니다. 가진통은 임신 초기부터 발생할 수 있으며, 병적인 상황이라기보다는 임신 중에 흔히 생길 수 있는 자궁 수축 증상입니다. 가진통은 분만으로 진행될 진성 진통이 될 수도 있고, 점차 잦아들 수도 있습니다. 그러나 이를 구별하는 것은 매우 어렵습니다.</정의>
    <img>image/pelvis/False labor.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="비뇨의학과"/>
    <질환명 language="kor">간질성 방광염</질환명>
    <질환명 language="eng">Interstitial Cystitis</질환명>
    <증상>긴박뇨, 야간뇨, 복부 통증, 빈뇨, 방광 팽만</증상>
    <정의>간질성 방광염은 요로 감염 등 다른 명백한 원인 없이 방광 충만과 연관된 치골 상부 통증이 나타나고, 주간 빈뇨, 야간뇨, 절박뇨 등을 흔하게 동반하는 질환입니다.</정의>
    <img>image/pelvis/Interstitial Cystitis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="재활의학과"/>
    <질환명 language="kor">강직성 척추염</질환명>
    <질환명 language="eng">Ankylosing spondylitis</질환명>
    <증상>어깨의 통증, 관절통, 말초 통증, 골반 통증, 엉덩이 통증, 관절의 경직, 요통</증상>
    <정의>강직성 척추염은 척추의 주 병변이 특징인 만성 관절염의 일종입니다. 강직성에서 '강직'은 '뻣뻣해짐' 또는 '굳는 것'을 의미하고, 척추염은 말 그대로 '척추에 염증이 생기는 것'을 의미합니다. 척추 외에 엉덩이, 무릎, 어깨 등의 관절에도 염증을 일으킬 수 있습니다.</정의>
    <img>image/pelvis/Ankylosing spondylitis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="산부인과"/>
    <질환명 language="kor">계류 유산</질환명>
    <질환명 language="eng">Missed abortion</질환명>
    <증상>멍, 커지지 않는 자궁, 복부 통증, 체중감소, 유방의 퇴행, 비출혈, 비정상적 질출혈</증상>
    <정의>유산이란 태아가 생존이 가능한 시기 이전에 임신이 종결됨을 말하며, 그 중 계류 유산이란 자궁경부가 닫혀 있는 상태로 수일에서 수 주 동안 사망한 임신 산물이 자궁 내에 남아 있는 경우를 말합니다.</정의>
    <img>image/pelvis/Missed abortion.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="정형외과"/>
    <질환명 language="kor">고관절 이형성증</질환명>
    <질환명 language="eng">DDH (developmental dysplasia of the hip)</질환명>
    <증상>다리의 길이가 틀림, 귀두가 울혈됨, 오리걸음, 다리가 잘 안 벌어짐</증상>
    <정의>고관절 이형성증은 선천적 또는 발달성으로 비구의 발육 부진으로 인해, 고관절 내 공모양의 대퇴골 머리가 부분적으로 빠져있는 상태를 말합니다.</정의>
    <img>image/pelvis/DDH (developmental dysplasia of the hip).JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="정형외과"/>
    <질환명 language="kor">골괴사</질환명>
    <질환명 language="eng">Osteonecrosis</질환명>
    <증상>환부 부종, 환부 통증, 관절 운동성 감소, 병적골절</증상>
    <정의>골괴사는 뼈에 혈액 공급이 되지 않아 뼈조직이 죽어 가는 질환입니다. 신체의 어디서든 발생할 수 있지만, 주로 대퇴부(허벅지 뼈) 위쪽과 팔 위쪽, 어깨, 무릎, 척추 등에서 일어납니다. 모든 연령층에서 발병할 수 있습니다.</정의>
    <img>image/pelvis/Osteonecrosis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="산부인과"/>
    <질환명 language="kor">골반 염증성 질환</질환명>
    <질환명 language="eng">Pelvic inflammatory disease</질환명>
    <증상>열, 복부 통증, 골반 통증, 비정상적 질 분비물, 악취</증상>
    <정의>골반 염증성 질환은 질과 자궁 경관을 통해 세균이 침입하여 자궁 및 난관, 난소, 복강 내에 염증을 일으켜 발생하는 질환을 의미합니다.</정의>
    <img>image/pelvis/Pelvic inflammatory disease.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="산부인과"/>
    <질환명 language="kor">과다월경</질환명>
    <질환명 language="eng">Hypermenorrhea</질환명>
    <증상>어지러움, 빈혈</증상>
    <정의>과다월경은 월경량이 지나치게 많은 질환을 의미합니다. 월경이 7일 이상 계속되거나 월경량이 한 주기에 80mL 이상으로 과도하게 많아서 빈혈이 발생할 수 있습니다.</정의>
    <img>image/pelvis/Hypermenorrhea.JPG</img>
  </질병>
  <질병>
    <분류 부위별="골반" 진료과별="산부인과"/>
    <질환명 language="kor">과립막 세포종</질환명>
    <질환명 language="eng">Granulosa cell tumor</질환명>
    <증상>복부 통증, 무월경, 생식기 출혈, 덩어리가 만져짐, 복수, 비정상적 질출혈, 성조숙증</증상>
    <정의>과립막 세포종이란 난포를 구성하는 세포인 여포상피에서 유래된 과립막 세포에 발생하는 악성 종양입니다. 난소의 악성 종양 중 2~5%를 차지하는 비교적 드문 질환으로 조직학적 특징에 따라 성인형과 소아형으로 분류되며 성인형이 90%를 차지합니다.</정의>
    <img>image/pelvis/Granulosa cell tumor.JPG</img>
  </질병>
  
  <!--귀-->
  <질병>
    <분류 부위별="귀" 진료과별="이비인후과"/>
    <질환명 language="kor">감각신경성 난청</질환명>
    <질환명 language="eng">Sensorineural hearing loss</질환명>
    <증상>청력장애, 이명, 어지러움</증상>
    <정의>감각신경성 난청은 달팽이관의 청각세포로부터 뇌의 청각을 담당하는 부위까지의 신경 부위에 이상이 생겨 청력이 저하되는 현상을 의미합니다.</정의>
    <img>image/ear/Sensorineural hearing loss.JPG</img>
  </질병>
  <질병>
    <분류 부위별="귀" 진료과별="감염내과"/>
    <질환명 language="kor">거대세포 바이러스 질환</질환명>
    <질환명 language="eng">Cytomegaloviral diseases</질환명>
    <증상>정신 지체, 난청, 청력장애, 무증상, 열, 피로감, 태아 저체중, 궤양</증상>
    <정의>거대세포 바이러스 질환은 헤르페스 바이러스 중 하나인 제5형 인간 헤르페스 바이러스(Human Herpesvirus 5; HHV-5)에 감염된 질환입니다. 다른 헤르페스 바이러스처럼 일정 기간의 잠복기를 거친 후 활동합니다.</정의>
    <img>image/ear/Cytomegaloviral diseases.JPG</img>
  </질병>
  <질병>
    <분류 부위별="귀" 진료과별="이비인후과"/>
    <질환명 language="kor">고막염</질환명>
    <질환명 language="eng">Myringitis</질환명>
    <증상>고막에 수포형성, 청력장애, 이명, 이물감, 발적</증상>
    <정의>고막염은 고막에 생기는 염증을 의미합니다.</정의>
    <img>image/ear/Myringitis.JPG</img>
  </질병>
  <질병>
    <분류 부위별="귀" 진료과별="이비인후과"/>
    <질환명 language="kor">급성 중이염</질환명>
    <질환명 language="eng">Acute otitis media</질환명>
    <증상>고름, 이폐색감, 청력장애, 열, 이명, 환부의 분비물, 두통, 귀의 통증</증상>
    <정의>급성 중이염은 귀의 고막 안의 공간인 중이(중간 귀)가 감염되어 급성 염증이 발생한 것을 의미합니다. 대부분 감기의 후유증으로 발생합니다. 유소아에게 가장 흔하게 나타나는 감염 질환 중 하나입니다.</정의>
    <img>image/ear/Acute otitis media.JPG</img>
  </질병>
  <질병>
    <분류 부위별="귀" 진료과별="이비인후과"/>
    <질환명 language="kor">난청</질환명>
    <질환명 language="eng">hearing loss</질환명>
    <증상>청력장애, 이명, 어지러움, 귀의 통증</증상>
    <정의>난청은 말, 소리를 듣는 데 어려움이 있는 증상을 의미합니다. 난청은 진단명이라기보다는 잘 들리지 않는 증상 자체를 말합니다. 난청의 원인은 매우 다양하며, 유발 원인에 따라 여러 진단명이 있습니다.</정의>
    <img>image/ear/hearing loss.JPG</img>
  </질병>
  <질병>
    <분류 부위별="귀" 진료과별="이비인후과"/>
    <질환명 language="kor">노인성 난청</질환명>
    <질환명 language="eng">Presbycusis</질환명>
    <증상>청력장애</증상>
